version: '3'

services:
  rtmp:
    build: ./docker/rtmp
    container_name: 360-rtmp-server
    volumes:
      - ./public/live:/usr/local/nginx/html/hls
      - ./docker/rtmp/nginx.conf:/etc/nginx/nginx.conf
    environment:
      TZ: Asia/Tokyo
    ports:
      - 1935:1935

  web:
    build: ./docker/web
    container_name: 360-web-server
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/html/public
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: Asia/Tokyo
